export const metal_list = ["Menos Bronze",
"Valsena Iron",
"Granz Steel",
"Laurent Silver",
"Wendel Silver",
"Beiser Gold",
"Ishe Platinum",
"Lorimar Iron",
"Altena Alloy",
"Maia Lead",
"Orichalcum"
];

export const wood_list = ["Oak Wood",
"Holly Wood",
"Baobab Wood",
"Ebony Wood",
"Maple Wood",
"Dior Wood",
"Ash Wood",
"Fossil Wood"
];

export const stone_list = ["Marble",
"Obsidian",
"Pedan Stone",
"Gaia's Tears"
];

export const hide_list = ["Animal Hide",
"Gator Skin",
"Centaur Hide",
"Dragon Skin"
];

export const scales_list = ["Fish Scales",
"Lizard Scales",
"Snake Scales",
"Dragon Scales"
];

export const bone_list = ["Animal Bone",
"Ivory",
"Cursed Bone",
"Fossil"
];

export const fabric_list = ["Topple Cotton",
"Sultan's Silk",
"Judd Hemp",
"Altena Felt"
];

export const rock_list = ["Jacobini Rock",
"Halley Rock",
"Ankh Rock",
"Vinek Rock",
"Tuttle Rock",
"Nemesis Rock",
"Biella Rock",
"Swifte Rock"
];

export const misc_list = ["Adamantite",
"Fullmetal",
"Coral",
"Tortoiseshell",
"Seashell",
"Emerald",
"Pearl",
"Lapis Lazuli"
];

export const coin_list = ["Wisp Gold",
"Shade Gold",
"Dryad Gold",
"Aura Gold",
"Salamander Gold",
"Gnome Gold",
"Jinn Gold",
"Undine Gold",
"Wisp Silver",
"Shade Silver",
"Dryad Silver",
"Aura Silver",
"Salamander Silver",
"Gnome Silver",
"Jinn Silver",
"Undine Silver"
];

export const mana_stone_list = ["Firestone",
"Earthstone",
"Windstone",
"Waterstone"
];

export const mana_crystal_list = ["Sun Crystal",
"Moon Crystal",
"Glow Crystal",
"Chaos Crystal"
];

export const seed_list = ["Round Seed",
"Oblong Seed",
"Crooked Seed",
"Big Seed",
"Small Seed",
"Long Seed",
"Flat Seed",
"Spiny Seed"
];

export const produce_list = ["Bellgrapes",
"Diceberry",
"Mangolephant",
"Loquat-Shoe",
"Pear o' Heels",
"Squalphin",
"Citrisquid",
"Springanana",
"Peach Puppy",
"Apricat",
"Applesock",
"Whalamato",
"Pine o'Clock",
"Fishy Fruit",
"Boarmelon",
"Rhinoloupe",
"Orcaplant",
"Garlicrown",
"Honey Onion",
"Sweet Moai",
"Spiny Carrot",
"Conchurnip",
"Cornflower",
"Cabbadillo",
"Needlettuce",
"Cherry Bombs",
"Masked Potato",
"Lilipods",
"Rocket Papaya",
"Orange'opus",
"Bumpkin",
"Heart Mint",
"Spade Basil",
"Dialaurel",
"Gold Clover",
"Mush-in-a-Box",
"Toadstoolshed"
];

export const meat_list = ["Animal Meat",
"Bug Meat",
"Lizard Meat",
"Fish Meat",
"Bird Meat",
"Morph Meat",
"Demon Meat",
"Dragon Steak",
"Odd Meat",
"Magical Meat",
"Rotton Meat"
];

export const fang_list =["Sharp Claw",
"Poison Fang",
"Giant's Horn",
"Pincer",
"Healing Claw",
"Zombie Claw",
"Vampire Fang"
];

export const eye_list =["Little Eye",
"Sleepy Eye",
"Silly Eye",
"Dangerous Eye",
"Angry Eye",
"Blank Eye",
"Creepy Eye",
"Wicked Eye"
];

export const feather_list = ["Angel Feather",
"Raven Feather",
"Clear Feather",
"Moth Wing",
"Flaming Quill",
"White Feather"
];

export const bottle_list = ["Aroma Oil",
"Dragon Blood",
"Acid",
"Holy Water",
"Ether"
];

export const vial_list = ["Mercury",
"Stinky Breath",
"Ghost's Howl",
"Dragon's Breath",
"Damsel's Sigh"
];

export const urn_list =["Electricity",
"Moss",
"Ear of Wheat"
];

export const pellet_list = ["Baked Roach",
"Blackened Bat"
];

export const powder_list =["Sulfur",
"Poison Powder",
"Sleepy Powder",
"Knockout Dust",
"Rust",
"Grave Dirt",
"Ash"
];

export const pouch_list = ["Hairball",
"Needle",
"Mirror Piece",
"Wad of Wool",
"Messy Scroll",
];

export const misc_secondary_list = ["Greenball Bun",
"Tako Bug"
];

export const primaries = [
    metal_list,
    wood_list,
    stone_list,
    hide_list,
    scales_list,
    bone_list,
    fabric_list,
    rock_list,
    misc_list
];

export const primaries_names =[
    "metals",
    "woods",
    "stones",
    "hides",
    "scales",
    "bones",
    "fabrics",
    "rocks",
    "misc"
];

export const secondaries = [
    coin_list,
    mana_stone_list,
    mana_crystal_list,
    seed_list,
    produce_list,
    meat_list,
    fang_list,
    eye_list,
    feather_list,
    bottle_list,
    vial_list,
    urn_list,
    pellet_list,
    powder_list,
    pouch_list,
    misc_secondary_list
];
export const secondaries_names = [
    "coins",
    "mana stones",
    "mana crystals",
    "seeds",
    "produces",
    "meats",
    "fangs and claws",
    "eyes",
    "feathers",
    "bottles",
    'vials',
    "urns",
    "pellets",
    "powders",
    "pouches",
    "secondary misc"
];

export const element_list =["Wisp",
    "Shade",
    "Dryad",
    "Aura",
    "Salamander",
    "Gnome",
    "Jinn",
    "Undine",
];

export const area_type =["Circle",
    "Donut",
    "Fan",
    "Line",
    "Random",
    "Sphere",
    "Control"
];

export const target_type =["Fire",
    "Lock"
];

export const instrument_type =[
    "Harp",
    "Marimba",
    "Flute",
    "Drum"
];

export const attack_shape_map = [["Sphere Fire", "Sphere Lock", "Sphere Fire", "Sphere Fire", "Line Fire", "Control Fire", "Control Lock", "Control Fire"],
["Sphere Lock", "Sphere Lock", "Sphere Fire", "Line Lock", "Line Fire", "Line Lock", "Control Lock", "Control Lock"],
["Sphere Fire", "Sphere Fire", "Fan Fire", "Fan Fire", "Line Lock", "Control Fire", "Line Fire", "Control Fire"],
["Sphere Fire", "Fan Fire", "Sphere Fire", "Line Fire", "Fan Fire", "Line Fire", "Random Fire", "Control Fire"],
["Circle Fire", "Fan Fire", "Fan Lock", "Fan Lock", "Fan Fire", "Random Lock", "Line Fire", "Control Fire"],
["Circle Fire", "Fan Fire", "Circle Fire", "Random Fire", "Fan Fire", "Donut Fire", "Random Fire", "Random Fire"],
["Circle Lock", "Circle Lock", "Fan Fire", "Fan Fire", "Random Lock", "Random Fire", "Donut Lock", "Donut Lock"],
["Circle Fire", "Circle Lock", "Circle Fire", "Circle Fire", "Donut Fire", "Donut Fire", "Donut Lock", "Donut Fire"]];

export const harp_material_map = [["Menos Bronze", 3, 2, 6],
["Valsena Iron", 3, 1, 13],
["Granz Steel", 2, 1, 20],
["Laurent Silver", 2, 2, 27],
["Wendel Silver", 3, 2, 34],
["Beiser Gold", 3, 1, 41],
["Ishe Platinum", 2, 1, 48],
["Lorimar Iron", 2, 2, 55],
["Altena Alloy", 5, 2, 62],
["Maia Lead", 5, 3, 6],
["Orichalcum", 2, 2, 34],
["Oak Wood", 3, 3, 7],
["Holly Wood", 2, 3, 14],
["Baobab Wood", 3, 3, 21],
["Ebony Wood", 2, 3, 28],
["Maple Wood", 3, 3, 49],
["Dior Wood", 2, 3, 63],
["Ash Wood", 1, 3, 35],
["Fossil Wood", 0, 3, 56],
["Marble", 1, 1, 15],
["Obsidian", 1, 2, 29],
["Pedan Stone", 0, 2, 43],
["Gaia's Tears", 0, 1, 57],
["Animal Hide", 0, 0, 4],
["Gator Skin", 0, 1, 11],
["Centaur Hide", 0, 2, 18],
["Dragon Skin", 0, 3, 25],
["Fish Scales", 0, 0, 5],
["Lizard Scales", 1, 1, 19],
["Snake Scales", 2, 2, 26],
["Dragon Scales", 3, 3, 61],
["Animal Bone", 0, 0, 16],
["Ivory", 1, 0, 37],
["Cursed Bone", 2, 0, 44],
["Fossil", 3, 0, 58],
["Topple Cotton", 3, 3, 3],
["Sultan's Silk", 3, 2, 7],
["Judd Hemp", 3, 1, 10],
["Altena Felt", 3, 0, 14],
["Jacobini Rock", 4, 4, 7],
["Halley Rock", 5, 4, 14],
["Ankh Rock", 6, 4, 21],
["Vinek Rock", 6, 5, 28],
["Tuttle Rock", 6, 6, 35],
["Nemesis Rock", 5, 6, 42],
["Biella Rock", 4, 6, 49],
["Swifte Rock", 4, 5, 56],
["Adamantite", 4, 4, 8],
["Fullmetal", 1, 1, 18],
["Coral", 2, 2, 8],
["Tortoiseshell", 2, 2, 8],
["Seashell", 2, 2, 8],
["Emerald", 1, 2, 36],
["Pearl", 1, 2, 36],
["Lapis Lazuli", 1, 2, 36]];

export const marimba_material_map = [["Menos Bronze", 4, 5, 7],
["Valsena Iron", 4, 6, 13],
["Granz Steel", 5, 6, 19],
["Laurent Silver", 5, 5, 25],
["Wendel Silver", 4, 5, 31],
["Beiser Gold", 4, 6, 37],
["Ishe Platinum", 5, 6, 43],
["Lorimar Iron", 5, 5, 49],
["Altena Alloy", 2, 5, 55],
["Maia Lead", 3, 5, 7],
["Orichalcum", 5, 5, 31],
["Oak Wood", 4, 4, 8],
["Holly Wood", 5, 4, 14],
["Baobab Wood", 4, 4, 20],
["Ebony Wood", 5, 4, 26],
["Maple Wood", 4, 4, 44],
["Dior Wood", 5, 4, 56],
["Ash Wood", 6, 4, 32],
["Fossil Wood", 7, 4, 50],
["Marble", 6, 6, 13],
["Obsidian", 6, 5, 25],
["Pedan Stone", 7, 5, 37],
["Gaia's Tears", 7, 6, 49],
["Animal Hide", 7, 7, 3],
["Gator Skin", 7, 6, 9],
["Centaur Hide", 7, 5, 15],
["Dragon Skin", 7, 4, 21],
["Fish Scales", 7, 7, 6],
["Lizard Scales", 6, 6, 18],
["Snake Scales", 5, 5, 24],
["Dragon Scales", 4, 4, 54],
["Animal Bone", 7, 7, 13],
["Ivory", 6, 7, 31],
["Cursed Bone", 5, 7, 37],
["Fossil", 4, 7, 49],
["Topple Cotton", 4, 4, 3],
["Sultan's Silk", 4, 5, 6],
["Judd Hemp", 4, 6, 9],
["Altena Felt", 4, 7, 12],
["Jacobini Rock", 3, 3, 6],
["Halley Rock", 2, 3, 12],
["Ankh Rock", 1, 3, 18],
["Vinek Rock", 1, 2, 24],
["Tuttle Rock", 1, 1, 30],
["Nemesis Rock", 2, 1, 36],
["Biella Rock", 3, 1, 42],
["Swifte Rock", 3, 2, 48],
["Adamantite", 3, 3, 8],
["Fullmetal", 1, 6, 8],
["Coral", 6, 5, 8],
["Tortoiseshell", 6, 5, 8],
["Seashell", 6, 2, 8],
["Emerald", 6, 5, 31],
["Pearl", 6, 5, 31],
["Lapis Lazuli", 6, 5, 31]];

export const flute_material_map = [["Menos Bronze", 4, 2, 8],
["Valsena Iron", 4, 1, 16],
["Granz Steel", 5, 1, 24],
["Laurent Silver", 5, 2, 32],
["Wendel Silver", 4, 2, 40],
["Beiser Gold", 4, 1, 48],
["Ishe Platinum", 5, 1, 56],
["Lorimar Iron", 5, 2, 64],
["Altena Alloy", 5, 5, 72],
["Maia Lead", 5, 5, 8],
["Orichalcum", 5, 2, 40],
["Oak Wood", 4, 3, 9],
["Holly Wood", 5, 3, 17],
["Baobab Wood", 4, 3, 25],
["Ebony Wood", 5, 3, 33],
["Maple Wood", 4, 3, 57],
["Dior Wood", 5, 3, 73],
["Ash Wood", 6, 3, 41],
["Fossil Wood", 7, 3, 65],
["Marble", 6, 1, 18],
["Obsidian", 6, 2, 34],
["Pedan Stone", 7, 2, 50],
["Gaia's Tears", 7, 1, 66],
["Animal Hide", 7, 0, 4],
["Gator Skin", 7, 1, 12],
["Centaur Hide", 7, 2, 20],
["Dragon Skin", 7, 3, 28],
["Fish Scales", 7, 0, 6],
["Lizard Scales", 6, 1, 22],
["Snake Scales", 5, 2, 30],
["Dragon Scales", 4, 3, 70],
["Animal Bone", 7, 0, 17],
["Ivory", 6, 0, 41],
["Cursed Bone", 5, 0, 49],
["Fossil", 4, 0, 65],
["Topple Cotton", 4, 3, 4],
["Sultan's Silk", 4, 2, 8],
["Judd Hemp", 4, 1, 12],
["Altena Felt", 4, 0, 16],
["Jacobini Rock", 3, 4, 8],
["Halley Rock", 3, 5, 16],
["Ankh Rock", 3, 6, 24],
["Vinek Rock", 2, 6, 32],
["Tuttle Rock", 1, 3, 40],
["Nemesis Rock", 1, 5, 48],
["Biella Rock", 1, 4, 56],
["Swifte Rock", 2, 4, 64],
["Adamantite", 3, 4, 10],
["Fullmetal", 6, 1, 10],
["Coral", 4, 1, 10],
["Tortoiseshell", 4, 1, 10],
["Seashell", 4, 1, 10],
["Emerald", 6, 2, 42],
["Pearl", 6, 2, 42],
["Lapis Lazuli", 6, 2, 42]];

export const drum_material_map = [["Menos Bronze", 3, 5, 3],
["Valsena Iron", 3, 6, 8],
["Granz Steel", 2, 6, 13],
["Laurent Silver", 2, 5, 18],
["Wendel Silver", 3, 5, 23],
["Beiser Gold", 3, 6, 28],
["Ishe Platinum", 2, 6, 33],
["Lorimar Iron", 2, 5, 38],
["Altena Alloy", 2, 2, 43],
["Maia Lead", 3, 3, 3],
["Orichalcum", 2, 5, 23],
["Oak Wood", 3, 4, 6],
["Holly Wood", 2, 4, 11],
["Baobab Wood", 3, 4, 16],
["Ebony Wood", 2, 4, 21],
["Maple Wood", 3, 4, 36],
["Dior Wood", 2, 4, 46],
["Ash Wood", 1, 4, 26],
["Fossil Wood", 0, 4, 41],
["Marble", 1, 1, 8],
["Obsidian", 1, 5, 18],
["Pedan Stone", 0, 5, 28],
["Gaia's Tears", 0, 1, 38],
["Animal Hide", 0, 7, 6],
["Gator Skin", 0, 6, 11],
["Centaur Hide", 0, 5, 16],
["Dragon Skin", 0, 4, 21],
["Fish Scales", 0, 7, 4],
["Lizard Scales", 1, 6, 14],
["Snake Scales", 2, 5, 19],
["Dragon Scales", 3, 4, 44],
["Animal Bone", 0, 7, 12],
["Ivory", 1, 7, 27],
["Cursed Bone", 2, 7, 32],
["Fossil", 3, 7, 42],
["Topple Cotton", 3, 4, 5],
["Sultan's Silk", 3, 5, 10],
["Judd Hemp", 3, 6, 15],
["Altena Felt", 3, 7, 20],
["Jacobini Rock", 4, 3, 4],
["Halley Rock", 4, 2, 9],
["Ankh Rock", 4, 1, 14],
["Vinek Rock", 5, 1, 19],
["Tuttle Rock", 6, 1, 24],
["Nemesis Rock", 6, 2, 29],
["Biella Rock", 6, 4, 34],
["Swifte Rock", 5, 4, 39],
["Adamantite", 4, 3, 6],
["Fullmetal", 6, 6, 6],
["Coral", 1, 6, 6],
["Tortoiseshell", 1, 6, 8],
["Seashell", 1, 6, 8],
["Emerald", 1, 5, 24],
["Pearl", 1, 5, 24],
["Lapis Lazuli", 1, 5, 24]];
